application: thenorthgatealternative
version: 1
runtime: python27
api_version: 1
default_expiration: "365d"
threadsafe: yes

inbound_services:
- warmup

handlers:
- url: /favicon\.ico
  mime_type: image/x-icon
  static_files: app/static/img/favicon.ico
  upload: app/static/img/favicon\.ico

- url: /static
  static_dir: app/static

- url: /gae_mini_profiler/static
  static_dir: libs/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: libs.gae_mini_profiler.main.application

- url: .*
  script: app.wsgi

